export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const DELETE_TODO_LOADING = "DELETE_TODO_LOADING";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";

export const TOGGLE_TODO_STATUS_LOADING = "TOGGLE_TODO_STATUS_LOADING";
export const TOGGLE_TODO_STATUS_SUCCESS = "TOGGLE_TODO_STATUS_SUCCESS";
export const TOGGLE_TODO_STATUS_ERROR = "TOGGLE_TODO_STATUS_ERROR";

export const TODOS_UPDATED = "TODOS_UPDATED";

export const TODO_PRIORITY = {
  HIGH: 1,
  NORMAL: 2,
  LOW: 3
};
