export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_STARTED = "LOGOUT_STARTED";
export const LOGOUT_COMPLETED = "LOGOUT_COMPLETED";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
